/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: VIASS (https://sketchfab.com/VIASS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viass-delivery-man-02fbdce233f349408df7e42437b8ed30
Title: VIASS Delivery man
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import scene from '../assets/3d/delivery_man.glb';

const DeliveryMan = ({currentAnimation,...props}) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop());

        if (actions[currentAnimation]) {
            actions[currentAnimation].play();
        }
    },[actions,currentAnimation])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
                    <group name="c9d70bfdaa5e4b2eab67082731fd10d3fbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Object_4">
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_6"
                                        geometry={nodes.Object_6.geometry}
                                        material={materials.lambert2}
                                        skeleton={nodes.Object_6.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.mat_deliveryman}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <group name="Character">
                                        <group name="DeliveryMan_mesh" />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

export default DeliveryMan;


