/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gostbento (https://sketchfab.com/gostbento)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/delivery-robot-4dbac67355174751801fb1f6e8dc6230
Title: Delivery robot
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import scene from '../assets/3d/delivery_robot.glb';

const Delivery = ({currentAnimation, ...props}) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(scene);
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        console.log(actions.Animation);
        Object.values(actions).forEach((action) => action.stop());
        
        if(actions[currentAnimation]){
            actions['Animation'].play();
        }
        
    }, [actions,currentAnimation]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
                    <group name="6e734d7dca644fcab9b5a40628918a66fbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Cube" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                <group
                                    name="Armature"
                                    position={[0, -117.909, 0]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}>
                                    <group name="Object_6">
                                        <primitive object={nodes._rootJoint} />
                                        <skinnedMesh
                                            name="Object_9"
                                            geometry={nodes.Object_9.geometry}
                                            material={materials['Material.002']}
                                            skeleton={nodes.Object_9.skeleton}
                                        />
                                        <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                                    </group>
                                </group>
                                <group
                                    name="Crane_Rig"
                                    position={[-420.728, -117.909, 1008.994]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={274.014}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

export default Delivery;
